name: crampanion
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.1
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/splash_image.png
